### ISSUE TITLE
[Bug]: Unresolvable dependencies from scratch

### ISSUE THREAD

**Issue by bvn13** [ChrisUser/cra-template-complete-web-app#2]
### What happened?

Create react app with this template
`npm install` fails with much errors

### Version

fresh

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChrisUser** [comment]
Hi @bvn13, I've released a new project version which should fix this issue. I've already tested it but please try it and let me know if the same is true for you.

[This](https://github.com/ChrisUser/cra-template-complete-web-app/commit/668945ac4410d905322855e21c6c2855206004bb) is the commit that solved all the problems linked with the creation process.

**Comment by bvn13** [comment]
It works now

**Comment by ChrisUser** [comment]
Amazing! Thanks for taking the time to report this bug.

**Comment by JuanEspin0sa** [comment]
I'm still having the same issue when running `npx create-react-app my-app --template complete-web-app`.  Is there a specific way I should be using to pull the latest version with this fix?

**Comment by ChrisUser** [comment]
Hi @JuanEspin0sa, sorry for the late reply.

I've published a new release ([v1.1.16](https://github.com/ChrisUser/cra-template-complete-web-app/commit/76a8ddfec8de83e3a2fb5553d042b628cedb3f52)) that includes a fix described in https://github.com/facebook/create-react-app/issues/13080#issuecomment-1515280885. Let me know if it solves all your issues.

I'll soon publish a new template for a complete React app configuration using Vite as suggested by the React community.
Sadly Create React App seems like a [dead project](https://github.com/facebook/create-react-app/issues/13393), but I won't stop the support for this template yet.

**Comment by ChrisUser** [comment]
Going to close this one due to inactivity. Feel free to re-open in case the problem recurs.
